name: fyp
channels:
    - conda-forge
    - pytorch
    - defaults
dependencies:
    - python=3.10
    - pip
    - basemap
    - bottleneck
    - cartopy
    - cython
    - dask
    - h5py
    - ipython
    - jupyter
    - jupyterlab
    - matplotlib
    - pandas
    - scikit-learn
    - scikit-image
    - statsmodels
    - seaborn
    - tqdm
    - xarray
    - zarr
    - numcodecs
    - pytorch
    - torchvision
    - torchaudio
    - torchtext
    - opencv
    - librosa
    - pip:
        - ray[default]
        - ray[air]
        - ray[tune]
        - ray[rllib]
        - ray[serve]
        - gymnasium
        - numba
        - scipy
        - tensorboard
